stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - ./gradlew clean build

test:
  stage: test
  script:
    - ./gradlew test

deploy:
  stage: deploy
  script:
    - echo "Deployment step completed!"
